// Sylo API — prompt construction and output formatting.

import { ContextSnapshot } from './types'

export const AGENT_CONTEXT_SYSTEM_PROMPT = `You are generating a context handoff file for an AI coding agent. The developer is about to start a new agent session (Claude Code, Cursor, or Copilot) and needs the agent to understand their current task immediately — no clarifying questions, no re-explanation.

Generate a structured markdown file. Rules:
- Be specific: name exact files, line numbers, function names, variable names, error messages. Generic descriptions are useless.
- Be concise: under 350 words total. Agents have limited context windows.
- Be actionable: the "Next action" section must be specific enough that an agent can start executing it immediately.
- Do not add preamble, greetings, or meta-commentary. Output only the markdown.`

export const BRIEF_SYSTEM_PROMPT = `You are a developer's cognitive assistant. Output exactly 3 sentences separated by newlines. No preamble.
- Sentence 1: what the developer was doing (specific file, function, task — name exact identifiers)
- Sentence 2: the last meaningful decision or action visible in the code state
- Sentence 3: the single most concrete next step`

export function buildAgentContextPrompt(
  snapshot: ContextSnapshot,
  options?: { truncated?: boolean }
): string {
  const maxSurroundingLines = options?.truncated ? 40 : 60
  const maxDiffLines = options?.truncated ? 50 : 100

  const surrounding = snapshot.activeFile
    ? firstLines(snapshot.activeFile.surroundingCode, maxSurroundingLines)
    : ''

  return `Generate a Sylo context file from this workspace snapshot.

PROJECT: ${snapshot.workspaceName}
BRANCH: ${snapshot.git.branch ?? 'not a git repo'}
LAST COMMIT: ${snapshot.git.lastCommitMessage ?? 'none'}
RECENT COMMITS:
${snapshot.git.lastFiveCommits.map((c) => '- ' + c).join('\n') || 'none'}

ACTIVE FILE: ${snapshot.activeFile?.relativePath ?? 'none'} (line ${snapshot.activeFile?.cursorLine ?? 0})
LANGUAGE: ${snapshot.activeFile?.languageId ?? 'unknown'}
HAS UNSAVED CHANGES: ${snapshot.activeFile?.isDirty ?? false}

${
  snapshot.activeFile?.fullContent
    ? `FULL FILE CONTENT (${snapshot.activeFile.fullContent.split('\n').length} lines):\n\`\`\`${snapshot.activeFile.languageId}\n${snapshot.activeFile.fullContent}\n\`\`\``
    : `CODE AROUND CURSOR:\n\`\`\`${snapshot.activeFile?.languageId ?? ''}\n${surrounding}\n\`\`\``
}

${
  snapshot.activeFile?.selectionText
    ? `SELECTED CODE:\n\`\`\`\n${snapshot.activeFile.selectionText}\n\`\`\``
    : ''
}

GIT CHANGES (summary):
${snapshot.git.diffStat ?? 'no uncommitted changes'}

ACTIVE FILE DIFF:
${
  snapshot.git.activeDiff
    ? snapshot.git.activeDiff.split('\n').slice(0, maxDiffLines).join('\n')
    : 'no changes to this file'
}

ALL OPEN FILES:
${snapshot.openFiles.map((f) => '- ' + f.relativePath + (f.isDirty ? ' [unsaved]' : '')).join('\n')}

ERRORS AND WARNINGS:
${
  snapshot.diagnostics.length > 0
    ? snapshot.diagnostics
        .map(
          (d) => `${d.severity.toUpperCase()} [${d.source ?? 'unknown'}]: ${d.message} in ${d.file}:${d.line}`
        )
        .join('\n')
    : 'none'
}

${
  snapshot.existingContextFile
    ? `PREVIOUS CONTEXT FILE (for continuity):\n${snapshot.existingContextFile.slice(0, 800)}`
    : ''
}`
}

export function buildBriefPrompt(snapshot: ContextSnapshot, awayDurationMs: number): string {
  return `The developer was away from their editor for ${formatDuration(awayDurationMs)}. Give them a 3-sentence re-entry brief from this workspace snapshot.

PROJECT: ${snapshot.workspaceName}
BRANCH: ${snapshot.git.branch ?? 'not a git repo'}
LAST COMMIT: ${snapshot.git.lastCommitMessage ?? 'none'}

ACTIVE FILE: ${snapshot.activeFile?.relativePath ?? 'none'} (line ${snapshot.activeFile?.cursorLine ?? 0})
LANGUAGE: ${snapshot.activeFile?.languageId ?? 'unknown'}
HAS UNSAVED CHANGES: ${snapshot.activeFile?.isDirty ?? false}

CODE AROUND CURSOR:
\`\`\`${snapshot.activeFile?.languageId ?? ''}
${snapshot.activeFile?.surroundingCode ?? ''}
\`\`\`

${
  snapshot.activeFile?.selectionText
    ? `SELECTED CODE:\n\`\`\`\n${snapshot.activeFile.selectionText}\n\`\`\``
    : ''
}

ACTIVE FILE DIFF:
${snapshot.git.activeDiff ?? 'no changes to this file'}

ERRORS AND WARNINGS:
${
  snapshot.diagnostics.length > 0
    ? snapshot.diagnostics
        .map((d) => `${d.severity.toUpperCase()}: ${d.message} in ${d.file}:${d.line}`)
        .join('\n')
    : 'none'
}

OPEN FILES:
${snapshot.openFiles.map((f) => '- ' + f.relativePath).join('\n')}`
}

export function formatContextFile(raw: string, _snapshot: ContextSnapshot): string {
  const timestamp = new Date().toISOString()
  const comment = `<!-- Generated by Sylo at ${timestamp} -->\n\n`

  // Strip any accidental outer code fences the LLM might have added
  const clean = raw
    .replace(/^```(?:markdown|md)?\n?/, '')
    .replace(/\n?```$/, '')
    .trim()

  return comment + clean
}

export function formatDuration(ms: number): string {
  const minutes = Math.floor(ms / 60000)
  const hours = Math.floor(minutes / 60)
  if (hours > 0) return `${hours} hour${hours > 1 ? 's' : ''} ${minutes % 60} minutes`
  return `${minutes} minute${minutes !== 1 ? 's' : ''}`
}

function firstLines(text: string, max: number): string {
  const lines = text.split('\n')
  return lines.length <= max ? text : lines.slice(0, max).join('\n')
}
